export const MEAL_VISION_SCHEMA: Record<string, unknown> = {
  type: 'object',
  required: [
    'meal_type_guess',
    'ingredients_detected',
    'kcal_estimate_min',
    'kcal_estimate_max',
    'protein_g_min',
    'protein_g_max',
    'carbs_g_min',
    'carbs_g_max',
    'fat_g_min',
    'fat_g_max',
    'confidence_score',
    'user_warnings',
  ],
  additionalProperties: false,
  properties: {
    meal_type_guess: {
      type: 'string',
      enum: ['breakfast', 'lunch', 'dinner', 'snack', 'drink', 'dessert'],
    },
    ingredients_detected: {
      type: 'array',
      items: {
        type: 'object',
        required: [
          'label',
          'portion_estimate',
          'grams_estimate',
          'kcal_estimate',
          'protein_g',
          'carbs_g',
          'fat_g',
        ],
        additionalProperties: false,
        properties: {
          label: { type: 'string' },
          portion_estimate: { type: 'string' },
          grams_estimate: { type: 'number' },
          kcal_estimate: { type: 'number' },
          protein_g: { type: 'number' },
          carbs_g: { type: 'number' },
          fat_g: { type: 'number' },
        },
      },
    },
    kcal_estimate_min: { type: 'number' },
    kcal_estimate_max: { type: 'number' },
    protein_g_min: { type: 'number' },
    protein_g_max: { type: 'number' },
    carbs_g_min: { type: 'number' },
    carbs_g_max: { type: 'number' },
    fat_g_min: { type: 'number' },
    fat_g_max: { type: 'number' },
    confidence_score: { type: 'number' },
    user_warnings: { type: 'array', items: { type: 'string' } },
  },
}
